apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nativeRunner.serviceAccount }}
  namespace: {{ .Values.nativeRunner.namespace }}
  labels:
    app.kubernetes.io/part-of: glimmung-native-runner
    azure.workload.identity/use: "true"
  {{- if .Values.nativeRunner.serviceAccountClientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.nativeRunner.serviceAccountClientId | quote }}
  {{- end }}
